First PR
Gyrf921/Bank-Prototype pull request #1
Opened 2023-07-26 18:39 UTC by Gyrf921

Without test for scoring

2023-07-31 11:30 UTC, RedRad1sh requested changes

2023-07-31 11:30 UTC, RedRad1sh commented on BankPrototype/credit-conveyor/src/main/java/com/bankprototype/creditconveyor/service/impl/PrescoringCalculationImpl.java
> +    public List<LoanOfferDTO> createListLoanOffer(LoanApplicationRequestDTO LNR_DTO){
LNR_DTO - это не константа

2023-07-31 11:30 UTC, RedRad1sh commented on BankPrototype/credit-conveyor/src/main/java/com/bankprototype/creditconveyor/service/impl/ScoringCalculationImpl.java
> +
лог

2023-07-31 11:34 UTC, RedRad1sh requested changes

2023-07-31 11:34 UTC, RedRad1sh commented on BankPrototype/credit-conveyor/src/main/resources/application.properties
> +workPositionRateRule_TOP_MANAGER=4.0
Попробуй использовать Yaml вместо properties. И для чистоты все эти свойства вынеси в какое-нибудь родительское типа "scoringConfig"

2023-07-31 11:37 UTC, Gyrf921 commented on BankPrototype/credit-conveyor/src/main/java/com/bankprototype/creditconveyor/rule/IRateRule.java
> +public interface IRateRule {
Я просто где то это подсмотрел и такой "О, прикольно, можно и у себя поставить" 😅😅😅

2023-08-01 12:34 UTC, Gyrf921 commented on BankPrototype/credit-conveyor/src/main/resources/application.properties
> +workPositionRateRule_TOP_MANAGER=4.0
С yaml много головной боли получалось, @PropertySource он не поддерживает, тесты проваливает, в общем я вынес в отдельный файли на этом остановился

2023-08-01 13:03 UTC, Gyrf921 commented on BankPrototype/credit-conveyor/src/main/java/com/bankprototype/creditconveyor/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(errorDetails, HttpStatus.BAD_REQUEST);
Так он вроде есть statusCode называется, или я что-то не правильно понял... Сегодня на встрече разберём

2023-08-02 08:35 UTC, RedRad1sh approved these changes

2023-08-02 08:35 UTC, RedRad1sh commented on BankPrototype/credit-conveyor/src/main/java/com/bankprototype/creditconveyor/exception/ErrorDetails.java
> +    private int business_error_code;
нейминг стиль

2023-08-02 08:35 UTC, RedRad1sh commented on BankPrototype/credit-conveyor/src/main/java/com/bankprototype/creditconveyor/web/controller/ConveyorController.java
> +    public List<LoanOfferDTO> calculationPossibleLoanOffers(@Valid @RequestBody LoanApplicationRequestDTO loanApplicationRequestDTO)
Опять не глагол в имени метода. В общем имя business code поправить под нейминг и calculate поставить. Можно мержить

2023-08-02 13:28 UTC, merged