MVP-4 Dossier first try
Gyrf921/Bank-Prototype pull request #10
Opened 2023-08-31 15:49 UTC by Gyrf921

First attempt to pass mvp 4

2023-08-31 17:43 UTC, RedRad1sh requested changes

2023-08-31 17:43 UTC, RedRad1sh commented on BankPrototype/dossier/pom.xml
> +        </dependency>
Можешь использовать для тестирования embeddedKafka из этого пакета.

Или почитай про TestContainers, с ними тестирование будет более полное. В целом их можно использовать и для бд и для любой другой внешней системы, которую можно поднять в докере при старте тестов.

2023-08-31 17:43 UTC, RedRad1sh commented on BankPrototype/dossier/src/main/java/com/bankprototype/dossier/service/impl/DossierConsumerImpl.java
> +    @KafkaListener(groupId = "dossier", topics = "finish_registration")
Вынеси groupId в конфигурацию. Названия топиков тоже стоит туда поместить

2023-08-31 17:43 UTC, RedRad1sh commented on BankPrototype/dossier/src/main/java/com/bankprototype/dossier/web/dto/EmailMassageDTO.java
> +package com.bankprototype.dossier.web.dto;
это у нас в package web не подходит, это кафка

2023-08-31 17:43 UTC, RedRad1sh commented on BankPrototype/deal/src/main/java/com/bankprototype/deal/web/dto/EmailMassageDTO.java
> +package com.bankprototype.deal.web.dto;
В этом package все же лежат dto для web по логике названия, а не кафка

2023-08-31 17:43 UTC, RedRad1sh commented on BankPrototype/dossier/src/main/java/com/bankprototype/dossier/service/impl/DossierConsumerImpl.java
> +            throw new RuntimeException(e);
Также необходимо логгировать все ошибки

2023-08-31 17:43 UTC, RedRad1sh commented on BankPrototype/deal/src/main/java/com/bankprototype/deal/web/dto/enumfordto/Theme.java
> +    application_denied,
Также не вижу реализации отправки сообщения по теме application_denied, нужно по ответу от credit-conveyor определять

2023-09-02 07:23 UTC, Gyrf921 commented on BankPrototype/dossier/src/main/java/com/bankprototype/dossier/web/dto/enamfordto/Theme.java
> +    application_denied,
Для соответствия с отправленным сообщением и намёком на "будущее расширение"

2023-09-06 17:46 UTC, RedRad1sh requested changes

2023-09-06 17:46 UTC, RedRad1sh commented on BankPrototype/dossier/src/main/resources/application-test.properties
> +topic-name.application-denied=application_denied
этот файл надо было создавать в test/resources

2023-09-06 17:46 UTC, RedRad1sh commented on BankPrototype/dossier/src/test/java/com/bankprototype/dossier/service/impl/DossierConsumerImplTest.java
> +        System.out.println("SendMailService received this EmailMassageDTO:" + emailCaptorValue);
много дублирования, ну хотя бы в отдельный метод можно было выделить. 
В случае похожих тестов, где различаются только входные и выходные параметры, можно создавать параметризованные тесты - аннотация @ParameterizedTest

2023-09-06 17:46 UTC, RedRad1sh commented on BankPrototype/deal/src/test/java/com/bankprototype/deal/web/controller/DocumentControllerTest.java
> +}
Все тесты в контроллерах сломаны:
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'topic-name.finish-registration' in value "${topic-name.finish-registration}"

2023-09-06 17:46 UTC, RedRad1sh commented on BankPrototype/dossier/src/main/java/com/bankprototype/dossier/exception/BadKafkaMessageException.java
> +@ResponseStatus(value = HttpStatus.UNPROCESSABLE_ENTITY)
А зачем это, если у нас тут нет контроллеров?

2023-09-06 17:46 UTC, RedRad1sh commented on BankPrototype/dossier/src/main/java/com/bankprototype/dossier/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
А зачем вообще этот класс нужен? У нас нет контроллеров и Rest

2023-09-06 17:46 UTC, RedRad1sh commented on BankPrototype/deal/src/main/java/com/bankprototype/deal/web/feign/CreditConveyorFeignClientFallbackFactory.java
> +                return null;
Надо было не null, а хотя бы ResponseEntity с кодом ошибки. Теперь у тебя в методе контроллера может падать NullPointerException, так как там это никак не обрабатывается. Вообще здесь можно было сразу бросать кастомный эксепшн вместо return

2023-09-09 08:39 UTC, RedRad1sh approved these changes

2023-09-09 17:57 UTC, merged